name: Cypress Automation Tests

on:
  workflow_dispatch:
    

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Replace with your required Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
